name: CI Deploy Staging

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/**'

jobs:
  deploy:
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: m219raptis/python-demoapp
      IMAGE_TAG: latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: build
        run: make image IMAGE_TAG=${{ env.IMAGE_TAG }}

      - name: 'Push to container registry'
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.D_REG_USER }} -p ${{ secrets.D_REG_PW }}
          make push

      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.STAGING_HOST }}
          username: ${{ secrets.D_SSH_USER }}
          key: ${{ secrets.D_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.D_REG_USER }} -p ${{ secrets.D_REG_PW }}
            docker image pull ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            docker ps | awk '/:${{ vars.STAGING_PORT }}/ {print $1}' | xargs -r docker stop | xargs -r docker rm
            docker container run -dp ${{ vars.STAGING_PORT }}:5008 -t ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

  trigger-tests:
    needs: deploy
    name: 'Trigger tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: trigger api tests
        env:
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: gh workflow run run-api-tests.yaml

